security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: userpass
                        roles: ['ROLE_USER']
                    admin:
                        password: root
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

            access_control:
                - { path: ^/admin, roles: ROLE_ADMIN }

            encoders:
                Symfony\Component\Security\Core\User\User: plaintext
                providers:
                    in_memory:
                        memory:
                users:
                    user:
                        password: userpass
                        roles: ['ROLE_USER']
                    admin:
                        password: root
                        roles: ['ROLE_ADMIN']
